### XRD ###
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: azureapps.crossplane.io
spec:
  group: crossplane.io
  names:
    kind: AzureApp
    plural: azureapps
  claimNames:
    kind: AzureAppClaim
    plural: azureappclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    resourceGroup:
                      type: string
                    subscription:
                      type: string
                    tenant:
                      type: string
                    managedIdentity:
                      type: string
                    storageAccount:
                      type: string
                    role:
                      type: string
            status:
              type: object
              properties:
                principalId:
                  type: string
---
### Composition ###
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
spec:
  compositeTypeRef:
    apiVersion: crossplane.io/v1alpha1
    kind: AzureApp
  resources:
    - name: resource-group
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        metadata:
          labels: 
            testing.upbound.io/example-name: resource-group
        spec:
          forProvider:
            location: West Europe
      patches:
        - fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.name"
    - name: storage-account
      base:
        apiVersion: storage.azure.upbound.io/v1beta1
        kind: Account
        spec:
          forProvider:
            accountKind: StorageV2
            accountReplicationType: LRS
            accountTier: Standard
            isHnsEnabled: true
            location: West Europe
            resourceGroupNameSelector:
              matchLabels:
                testing.upbound.io/example-name: resource-group
      patches:
        - fromFieldPath: "spec.parameters.storageAccount"
          toFieldPath: "metadata.name"
    - name: managed-identity
      base:
        apiVersion: managedidentity.azure.upbound.io/v1beta1
        kind: UserAssignedIdentity
        metadata:
          labels:
            testing.upbound.io/example-name: managed-identity
        spec:
          forProvider:
            location: West Europe
            resourceGroupNameSelector:
              matchLabels:
                testing.upbound.io/example-name: resource-group
      patches:
        - fromFieldPath: "spec.parameters.managedIdentity"
          toFieldPath: "spec.forProvider.name"
        - type: ToCompositeFieldPath
          fromFieldPath: "status.atProvider.principalId"
          toFieldPath: "status.principalId"
    - name: federated-credential
      base:
        apiVersion: managedidentity.azure.upbound.io/v1beta1
        kind: FederatedIdentityCredential
        spec:
          forProvider:
            issuer: "https://issuer"
            audience:
              - "api://AzureADTokenExchange"
            subject: "system:serviceaccount:namespace:application"
            parentIdSelector:
              matchLabels:
                testing.upbound.io/example-name: managed-identity
            resourceGroupNameSelector:
              matchLabels:
                testing.upbound.io/example-name: resource-group
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.managedIdentity"
          toFieldPath: "metadata.name"
    - name: role-assignment
      base:
        apiVersion: authorization.azure.upbound.io/v1beta1
        kind: RoleAssignment
        spec:
          forProvider:
            principalId: "" # this was previously unknown, but now it is patched in from the status.principalId field in the Composite Resource
            roleDefinitionName: Reader
            scope: "/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Storage/storageAccounts/example"
      patches:
        - fromFieldPath: "status.principalId"
          toFieldPath: "spec.forProvider.principalId"
        - fromFieldPath: "spec.parameters.role"
          toFieldPath: "spec.forProvider.roleDefinitionName"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.subscription"
              - fromFieldPath: "spec.parameters.resourceGroup"
              - fromFieldPath: "spec.parameters.storageAccount"
            strategy: string
            string:
              fmt: "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Storage/storageAccounts/%s"
---
### XR ###
apiVersion: crossplane.io
kind: AzureApp
metadata:
  name: example
spec:
  compositionRef:
    name: azure-apps
  parameters:
    resourceGroup: resource-group
    subscription: 12345678-aaaa-bbbb-cccc-123456789012
    managedIdentity: managed-identity
    storageAccount: example
    role: Reader